### ISSUE TITLE
Isues Rendering

### ISSUE THREAD

**Issue by PrettyDevelopers** [jcdcdev/jcdcdev.Umbraco.ReadingTime#15]
### Which jcdcdev.Umbraco.ReadingTime version are you using?

Latest

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

Latest 13

### Bug summary

<img width="1215" alt="Screenshot 2024-05-17 at 2 53 54 pm" src="https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/111720303/c8631b5b-4bd6-4cd5-99f0-dbc47e496fd4">
When on a document type with template rendering the value. Unlike others properties I can not get the value you.

Returning a string, var or anything it is either null or errors.

### Steps to reproduce

Just making a normal document type with template. Creating this field and rendering in the view @model.Value("NAME")
This is always null

### Expected result / actual result

"1 minute" value for read time
Actual result is null.

The only way I can get the value is delving into the models .properties IEnumerable<IPublishedProperty> and getting it out of that.

**Comment by PrettyDevelopers** [comment]
To add to this, this is what I see in debug
<img width="864" alt="Screenshot 2024-05-17 at 3 13 58 pm" src="https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/111720303/377f0887-568b-48c4-b398-b2b99eaa8868">

**Comment by jcdcdev** [comment]
Hi @PrettyDevelopers, thanks for taking time to report the issue you are experiencing.

I am unable to replicate this issue on the bundled [v13 test site](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/tree/main/src/TestSite.13).

`Model.Value("newsDynamicReadTime")`

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/6ec703ae-98cb-47d2-8b51-c43805dd21f9)

`Model.Value<ReadingTimeModel>("newsDynamicReadTime")`

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/1386bd82-a35c-411f-ad5b-988c92a60027)

### Next Steps

- Please can you confirm what is returned when calling `Model.Value<ReadingTimeModel>("newsDynamicReadTime")`?
- Please send any log files generated during the time of the error
- Please can you confirm this can be replicated on a clean install of Umbraco 13.3.0?

**Comment by PrettyDevelopers** [comment]
Hi.
No errors.
the using is not selected when I use it and the value output is not as you shown.
This can be replicated on the latest clean umbraco as well for me.

![Screenshot 2024-05-28 at 10 30 23 AM](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/111720303/2950bb7b-bfc2-44a9-b306-50409b9cb415)
The using is greyed out so does not seem to be using it
![Screenshot 2024-05-28 at 10 32 39 AM](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/111720303/eaa70c0e-3d00-4cbf-8cad-8d2e54a683bc)
The value in this case has 5 minutes in the admin but reporting 0 in debug
