### ISSUE TITLE
Read Time Data Type doesn't work when vary by culture is selected

### ISSUE THREAD

**Issue by jawood1** [jcdcdev/jcdcdev.Umbraco.ReadingTime#3]
### Which jcdcdev.Umbraco.ReadingTime version are you using?

0.1.1

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.2.0

### Bug summary

I'm not sure if this comes as a bug or feature request as you don't technically say it supports different cultures.

But when setting the field for the read time to vary by culture the read time doesn't get set against the field.

I've not had chance to delve into the code but thought I'd raise a ticket :)

### Steps to reproduce

- Set a readtime field and make it vary by culture.
- Save and publish the page.
- Field text doesn't update with the read time value.

### Expected result / actual result

Field will display readtime based on selected culture.

**Comment by jcdcdev** [comment]
Hi @jawood1, thanks for taking the time to raise this issue 😀

I will investigate variant support over the long weekend as it's something that _should_ work

**Comment by jcdcdev** [comment]
Hi @jawood1, version 0.2.0 should address the issue. Please let me know if it does :)

**Comment by jawood1** [comment]
Hi @jcdcdev 

Thank you for looking at it so quickly, I’ll jump on tomorrow and let you know! :)

**Comment by jawood1** [comment]
Hi @jcdcdev 

I've just checked this and it's now working correctly. Thanks again :)

One thing I can raise as an issue if needed but it seems that when the field is set to shared it always outputs as 1 minute :)

Many thanks,
Jonathan

**Comment by jcdcdev** [comment]
Hi @jawood1, nicely spotted! I'm not entirely sure what the best approach to take when dealing with invariant editors on a content type that varies by culture, but I've had a go at implementing something sensible for the next release.

<details>

<summary>Scenarios</summary>

## Version 0.2.0 (Current)

### 1.
**Given**: A content type varies by culture 
**And**: The Reading Time editor is invariant 
**When**: Calculating Reading Time
**Then**: Only invariant properties will be included in the calculation

### 2.
**Given**: A content type is invariant
**And**: The Reading Time editor is invariant (Umbraco prevents Varies by Culture here)
**When**: Calculating Reading Time
**Then**: All properties will be included in the calculation

### 3.
**Given**: A content type varies by culture 
**And**: A property editor is invariant 
**When**: Calculating Reading Time for a given culture
**Then**: The property editor's invariant (global) value is **wrongly** ignored


## Version 0.3.0 

- Retain scenario one
- Retain scenario two
- Fix scenario three

### 1.
**Given**: A content type varies by culture 
**And**: The Reading Time editor is invariant 
**When**: Calculating Reading Time
**Then**: Only invariant properties will be included in the calculation

### 2.
**Given**: A content type is invariant
**And**: The Reading Time editor is invariant (Umbraco prevents Varies by Culture here)
**When**: Calculating Reading Time
**Then**: All properties will be included in the calculation

### 3.
**Given**: A content type varies by culture 
**And**: A property editor is invariant 
**When**: Calculating Reading Time for a given culture
**Then**: The property editor's invariant (global) value **is included** in the calculation
</details>
<details>

<summary>The repo now includes an example page on the v13 test site that demonstrates this calculation</summary>

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/81ed5494-3cf0-4c22-88f4-474ddf54cf28)

Note the Grid Content contains 150 words whereas Invariant Text only contains 18

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/bf6770ff-0495-4366-9e10-f6781909cebb)

</details>

**Comment by jawood1** [comment]
Hi @jcdcdev yeah I understand your predicament it's a bit edge case but looking at the scenarios for 0.3.0 it make sense how you've done it and to only work out the invariant items looks like a nice solution :)
